apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mysql
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce