apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certmanager-staging
spec:
  acme:
    privateKeySecretRef:
      name: secret-certmanager-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: marlonmelgarejo@gmail.com
    solvers:
    - http01:
        ingress:
          class: nginx    